/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.IOFile;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Call;
import model.Conversation;

/**
 *
 * @author hieub
 */
public class FormThongKe extends javax.swing.JPanel {

    DefaultTableModel tm;
    private String fileConversation;
    private String fileCall;
    private List<Conversation> list;

    /**
     * Creates new form FormThongKe
     */
    public FormThongKe() {
        initComponents();
        setSize(900, 700);
        String col[] = {"Thống kê ID", "Số lượng"};
        tm = new DefaultTableModel(col,0);
        jTable1.setModel(tm);
        fileConversation = "src\\controller\\conversation.txt";
        fileCall = "src\\controller\\call.txt";
        
    }
    
    public boolean checkFormatNumber(String value, String text) {
        if(value.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ban chua nhap " + text);
            return false;
        }
        else {
            for(char c : value.toCharArray()) {
                if (!Character.isDigit(c)) {
                    JOptionPane.showMessageDialog(this, text + " khong hop le");
                    return false;
                }
            }
        }
        return true;
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textCallOfConversation = new javax.swing.JTextField();
        btConversation = new javax.swing.JButton();
        btCall = new javax.swing.JButton();
        btCallOfConversation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setText("Thống kê Conversation");

        jLabel2.setText("Thống kê Call");

        jLabel3.setText("Thống kê Call Of Conversation");

        btConversation.setText("Submit");
        btConversation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConversationActionPerformed(evt);
            }
        });

        btCall.setText("Submit");
        btCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCallActionPerformed(evt);
            }
        });

        btCallOfConversation.setText("Submit");
        btCallOfConversation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCallOfConversationActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btConversation, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(textCallOfConversation, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btCall, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(btCallOfConversation, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(textCallOfConversation, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCallOfConversation)
                    .addComponent(btCall)
                    .addComponent(btConversation))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btConversationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConversationActionPerformed
        list = IOFile.docra(fileConversation);
        tm.setRowCount(0);
        int length = list.size();
        if(length>0)
            tm.addRow(new Object[]{"Conversation", length});
        else 
            JOptionPane.showMessageDialog(this, "Không có cuộc hội thoại nào");
    }//GEN-LAST:event_btConversationActionPerformed

    private void btCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCallActionPerformed
        list = IOFile.docra(fileCall);
        tm.setRowCount(0);
        int length = list.size();
        if(length>0)
            tm.addRow(new Object[]{"Call", length});
        else 
            JOptionPane.showMessageDialog(this, "Không có cuộc gọi nào");
    }//GEN-LAST:event_btCallActionPerformed

    private void btCallOfConversationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCallOfConversationActionPerformed
        list = IOFile.docra(fileConversation);
        if(checkFormatNumber(textCallOfConversation.getText(), "Conversation Id")) {
            int conversationId = Integer.parseInt(textCallOfConversation.getText());
            int count = 0;
            tm.setRowCount(0);
            for(Conversation conversation:list) {
                if(conversation.getConversationId() == conversationId) {
                    count = conversation.getCallList().size();
                    break;
                }
            }
            if(count>0)
                tm.addRow(new Object[]{"Call of conversation", count});
            else 
                JOptionPane.showMessageDialog(this, "Không có cuộc gọi nào");
        }
    }//GEN-LAST:event_btCallOfConversationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCall;
    private javax.swing.JButton btCallOfConversation;
    private javax.swing.JButton btConversation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textCallOfConversation;
    // End of variables declaration//GEN-END:variables
}
